### ISSUE TITLE
Feature - Add Docker Export

### ISSUE THREAD

**Issue by ktraister** [jenkinsci/habitat-plugin#1]
It'd be sweet if we could add the ability to export Habitat packages into docker containers through this plugin. Currently, I'm calling the native shell {bash, powershell} to execute the command with

  \\$new_pkg="${workspace}/results/${env.PKG_FILE_NAME}"
  hab pkg export docker \\$new_pkg

It'd be great to perform this process automagically through the plugin with a 

  habitat task: 'export', format: 'docker', lastBuildFile: "${workspace}/results/last_build.env"

I'd be happy to help if you point me to an example of calling the shell commands in the code for the plugin

**Comment by skylerto** [comment]
Sounds like a useful feature indeed!

**Comment by skylerto** [comment]
We're using this piece of code to define which commands are available:

https://github.com/jenkinsci/habitat-plugin/blob/2c61c00c812d7382a8a2f1465b5d1617a03d656b/src/main/java/org/jenkinsci/plugins/habitat/HabitatExecutor.java#L125

**Comment by ktraister** [comment]
Created pull request #2 on this issue
