### ISSUE TITLE
Additional Functionality 

### ISSUE THREAD

**Issue by ktraister** [jenkinsci/habitat-plugin#4]
I'm creating this issue as a placeholder while I work on adding "hab config", "hab bldr job", "hab file", "hab origin", and "hab bldr channel" commands to the plugin. 

The goal of this is to prevent double work!

**Comment by skylerto** [comment]
Good stuff, I'm not sure of the use case for a few of these especially in the context of a pipeline plugin. Do you mind elaborating or walking me through your use case?

**Comment by ktraister** [comment]
It's a list I'm still fleshing out. A lot of the commands from hab are redundant, but I'd like to add anything that has value

**Comment by skylerto** [comment]
Agreed, I think we need to consider what value each piece brings. The scariest thing is going to heavy in features without use cases IMO.

**Comment by ktraister** [comment]
I agree, I think these are the last few commands that could add value to the plugin:

https://www.habitat.sh/docs/habitat-cli/#hab-config-apply
https://www.habitat.sh/docs/habitat-cli/#hab-config-show
https://www.habitat.sh/docs/habitat-cli/#hab-file-upload
https://www.habitat.sh/docs/habitat-cli/#hab-origin-key download/upload
https://www.habitat.sh/docs/habitat-cli/#hab-bldr-channel

**Comment by skylerto** [comment]
`hab config apply` and `hab file upload` with `--remote-sup` would for sure be useful!

`hab origin key` commands could be good as well, I see that as more habitat/jenkins configuration.

`hab bldr channel` is a good one as well, less of something I can see fitting into a pipeline, more as a pipeline utility. 

`hab config show` would be less useful imo, as it only shows the default configuration; I've never understood the use case for it in general.

**Comment by ktraister** [comment]
I saw "origin key" as giving the user the ability to recover from failures brought on due to key errors.

"hab config show" was something I thought about use for in a scripted pipeline, i.e
`hab_config = hab config show myorigin/mypkg/version/timestamp;
if "the-field-I-care-about" not in hab_config {
     hab config apply this_other_config
}`

**Comment by ktraister** [comment]
looks like "hab config show" is being handled in the plugin with "hab pkg config"; we'll leave that one out
