### ISSUE TITLE
Not sure how to get it going, 

### ISSUE THREAD

**Issue by sam1el** [jenkinsci/habitat-plugin#8]
I feel ridiculous asking this but, I couldn't find an answer anywhere. I have installed the plugin on my jenkins server. I can't find any way to configure it. When I try to use it as a build step, nothing happens. No boxes open or errors. Am I misunderstanding how this works? Do I only need a jenkinsfile in my repo?

Jenkins version 2.138.2
Plugin version  0.52

**Comment by skylerto** [comment]
I’m happy you asked! The plugin is meant to be used from a Jenkinsfile, I typically use the blue ocean plugin as well as it makes it super easy to setup pipelines! 

Have a watch of the video on this post, might help you out! 

https://blog.chef.io/2018/07/11/guest-post-announcing-new-jenkins-plugin-to-better-manage-habitat-packages/

https://youtu.be/dXrlqYzbUxE

**Comment by sam1el** [comment]
This video cleared up my confusion completely. I guess, seeing it as a selectable build step with no other way to manipulate the function threw me off.

**Comment by skylerto** [comment]
Awesome! Glad it helped, we're really trying to keep it opinionated. Otherwise we could quite quickly get lost in configuration hell. Which is a scary place!
