### ISSUE TITLE
Incorrect path during upload of .hart package.

### ISSUE THREAD

**Issue by kmott** [jenkinsci/habitat-plugin#9]
I have a build in Jenkins using habitat plugin that succeeded about 2 weeks ago, but as of this morning, it's failing here:

```
[... snip ...]
Setting Directory: /hab/svc/jenkins-slave/data/workspace/workspace/uepipeline-vault-policies_master/results/last_build.env
Artifact bluepipeline-vault-policies-0.1.1-20190103170144-x86_64-linux.hart found in: /hab/svc/jenkins-slave/data/workspace/workspace/uepipeline-vault-policies_master/results/last_build.env
Last Package: /hab/svc/jenkins-slave/data/workspace/workspace/uepipeline-vault-policies_master/results/last_build.env/bluepipeline-vault-policies-0.1.1-20190103170144-x86_64-linux.hart
Could not find hart /hab/svc/jenkins-slave/data/workspace/workspace/uepipeline-vault-policies_master/results/last_build.env/bluepipeline-vault-policies-0.1.1-20190103170144-x86_64-linux.hart
```

Note that it doesn't seem to be picking up the correct path to upload the .hart file from: `uepipeline-vault-policies_master` seems to be chomped at the beginning of the directory path.

My plugin version is: habitat-executor v0.5.3

**Comment by skylerto** [comment]
I believe this was due to a rework of how we're validating running on windows vs linux.

I've related a new version with some changes that will hopefully fix this.

https://github.com/jenkinsci/habitat-plugin/releases/tag/habitat-0.6.1

I'll check on the status of the builds and validate.
